[package]
name = "ygopru"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
repository.workspace = true
description.workspace = true
readme = "README.md"
keywords = ["ygopro"]

[workspace.package]
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/iamipanda/ygopru"
description = "A Rust rewrite of the YGOPro duel server."

[dependencies]
ygopro.workspace = true
ygopro-data.workspace = true
ygopro-handler.workspace = true
ygopro-core-wrapper.workspace = true
ygopro-derive.workspace = true
ygopro-external-server-bridge.workspace = true

[workspace.dependencies]
ygopro = { path = "./ygopro", default-features = false }
ygopro-data = { path = "./ygopro-data", default-features = false }
ygopro-handler = { path = "./ygopro-handler", default-features = false }
ygopro-core-wrapper = { path = "./ygopro-core-wrapper", default-features = false }
ygopro-derive = { path = "./ygopro-derive" }
ygopro-external-server-bridge = { path = "./ygopro-external-server-bridge", default-features = false }

[features]
default = [
    "zip",
    "card"
]
koishi = [
    "ygopro/koishi",
    "ygopro-core-wrapper/koishi"
]
zip = ["ygopro/zip"]
card = [
    "ygopro/card",
    "ygopro-core-wrapper/card",
    "ygopro-data/card",
    "ygopro-external-server-bridge/card",
    "ygopro-handler/card",
]
ygomobile_support = ["ygopro/ygomobile_support"]

[workspace]
default-members = ["ygopro"]
resolver = "2"
members = [
    "ygopro-data",
    "ygopro-derive",
    "ygopro-core-wrapper",
    "ygopro-handler",
    "ygopro",
    "ygoserver",
    "ygopro-toolkits",
    "ygopro-external-server-bridge"
]

[profile.release]
lto = true
strip = true
opt-level = 'z'
