[package]
name = "ygopru"
version = "0.1.0"
edition = "2024"

[dependencies]
ygopro = { path = "./ygopro", default-features = false }
ygopro-data = { path = "./ygopro-data", default-features = false }
ygopro-handler = { path = "./ygopro-handler" }
ygopro-core-wrapper = { path = "./ygopro-core-wrapper" }
ygopro-derive = { path = "./ygopro-derive" }
ygopro-external-server-bridge = { path = "./ygopro-external-server-bridge" }

[features]
default = [
    "zip",
    "card"
]
zip = ["ygopro/zip"]
card = ["ygopro/card", "ygopro-data/card"]

[workspace]
default-members = ["ygoserver"]
resolver = "2"
members = [
    "ygopro-data",
    "ygopro-derive",
    "ygopro-core-wrapper",
    "ygopro-handler",
    "ygopro",
    "ygopro-toolkits",
    "ygopro-external-server-bridge",
    "ygoserver"
]

[profile.release]
lto = true
strip = true
opt-level = 'z'
