[package]
name = "ygopro-toolkits"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ygopro-toolkits"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
glob = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio-stream = "0.1"
binrw = "0.13"
futures = "0.3"
base64 = "0.22"
bytes = "1"
log = "0.4"
pretty_env_logger = "0.5"
thiserror = "1"

ygopro-data.workspace = true
ygopro = { path = "../ygopro", default-features = false }
ygopro-core-wrapper = { path = "../ygopro-core-wrapper", default-features = false }
ygopro-handler = { path = "../ygopro-handler", default-features = false }
ygopro-external-server-bridge = { path = "../ygopro-external-server-bridge", default-features = false }

[features]
default = ["card", "zip"]
card = [
    "ygopro/card",
    "ygopro-core-wrapper/card",
    "ygopro-data/card",
    "ygopro-external-server-bridge/card",
    "ygopro-handler/card",
]
zip = ["ygopro/zip"]
