[package]
name = "ygopro-core-wrapper"
version = "0.1.0"
edition = "2024"
links = "ygopro-core"

[dependencies]
ygopro-data.workspace = true
rand = "0.8"
parking_lot = "0.12"
modular-bitfield = "0.13.1"

[build-dependencies]
cc = "1"
glob = "0.3"

[features]
default = []
card = ["ygopro-data/card"]
